[
  {
    "url": "https://api.github.com/repos/grpc/grpc/issues/comments/426739386",
    "html_url": "https://github.com/grpc/grpc/issues/16718#issuecomment-426739386",
    "issue_url": "https://api.github.com/repos/grpc/grpc/issues/16718",
    "id": 426739386,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQyNjczOTM4Ng==",
    "user": {
      "login": "mehrdada",
      "id": 900411,
      "node_id": "MDQ6VXNlcjkwMDQxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/900411?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mehrdada",
      "html_url": "https://github.com/mehrdada",
      "followers_url": "https://api.github.com/users/mehrdada/followers",
      "following_url": "https://api.github.com/users/mehrdada/following{/other_user}",
      "gists_url": "https://api.github.com/users/mehrdada/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mehrdada/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mehrdada/subscriptions",
      "organizations_url": "https://api.github.com/users/mehrdada/orgs",
      "repos_url": "https://api.github.com/users/mehrdada/repos",
      "events_url": "https://api.github.com/users/mehrdada/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mehrdada/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-10-03T18:09:55Z",
    "updated_at": "2018-10-03T18:09:55Z",
    "author_association": "CONTRIBUTOR",
    "body": "related to https://github.com/grpc/grpc/issues/16643"
  },
  {
    "url": "https://api.github.com/repos/grpc/grpc/issues/comments/436046373",
    "html_url": "https://github.com/grpc/grpc/issues/16718#issuecomment-436046373",
    "issue_url": "https://api.github.com/repos/grpc/grpc/issues/16718",
    "id": 436046373,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzNjA0NjM3Mw==",
    "user": {
      "login": "lidizheng",
      "id": 7394928,
      "node_id": "MDQ6VXNlcjczOTQ5Mjg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7394928?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lidizheng",
      "html_url": "https://github.com/lidizheng",
      "followers_url": "https://api.github.com/users/lidizheng/followers",
      "following_url": "https://api.github.com/users/lidizheng/following{/other_user}",
      "gists_url": "https://api.github.com/users/lidizheng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lidizheng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lidizheng/subscriptions",
      "organizations_url": "https://api.github.com/users/lidizheng/orgs",
      "repos_url": "https://api.github.com/users/lidizheng/repos",
      "events_url": "https://api.github.com/users/lidizheng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lidizheng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-05T21:43:39Z",
    "updated_at": "2018-11-05T21:43:39Z",
    "author_association": "CONTRIBUTOR",
    "body": "@biaken Hi,\r\n\r\nThe quick fix for this is read the client-side credential with `rb` flag:\r\n```\r\ntrusted_certs = open(private_crt_file, 'rb').read()\r\n```\r\nAnd it will work. As for exception surface for proper notification, as Mehrdad said, we are working on it at #16643."
  },
  {
    "url": "https://api.github.com/repos/grpc/grpc/issues/comments/437454865",
    "html_url": "https://github.com/grpc/grpc/issues/16718#issuecomment-437454865",
    "issue_url": "https://api.github.com/repos/grpc/grpc/issues/16718",
    "id": 437454865,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzNzQ1NDg2NQ==",
    "user": {
      "login": "lidizheng",
      "id": 7394928,
      "node_id": "MDQ6VXNlcjczOTQ5Mjg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7394928?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lidizheng",
      "html_url": "https://github.com/lidizheng",
      "followers_url": "https://api.github.com/users/lidizheng/followers",
      "following_url": "https://api.github.com/users/lidizheng/following{/other_user}",
      "gists_url": "https://api.github.com/users/lidizheng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lidizheng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lidizheng/subscriptions",
      "organizations_url": "https://api.github.com/users/lidizheng/orgs",
      "repos_url": "https://api.github.com/users/lidizheng/repos",
      "events_url": "https://api.github.com/users/lidizheng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lidizheng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-09T18:39:53Z",
    "updated_at": "2018-11-09T18:39:53Z",
    "author_association": "CONTRIBUTOR",
    "body": "In PR #16971, we believe there should be another fix separated from exception surfacing. An exception should be raised when the `grpc.ssl_channel_credentials` be called, instead of raising exception after passing credentials to `grpc.secure_channel`."
  },
  {
    "url": "https://api.github.com/repos/grpc/grpc/issues/comments/441750612",
    "html_url": "https://github.com/grpc/grpc/issues/16718#issuecomment-441750612",
    "issue_url": "https://api.github.com/repos/grpc/grpc/issues/16718",
    "id": 441750612,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MTc1MDYxMg==",
    "user": {
      "login": "lidizheng",
      "id": 7394928,
      "node_id": "MDQ6VXNlcjczOTQ5Mjg=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7394928?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lidizheng",
      "html_url": "https://github.com/lidizheng",
      "followers_url": "https://api.github.com/users/lidizheng/followers",
      "following_url": "https://api.github.com/users/lidizheng/following{/other_user}",
      "gists_url": "https://api.github.com/users/lidizheng/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lidizheng/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lidizheng/subscriptions",
      "organizations_url": "https://api.github.com/users/lidizheng/orgs",
      "repos_url": "https://api.github.com/users/lidizheng/repos",
      "events_url": "https://api.github.com/users/lidizheng/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lidizheng/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-26T18:42:50Z",
    "updated_at": "2018-11-26T18:42:50Z",
    "author_association": "CONTRIBUTOR",
    "body": "This issue should be fixed by PR #17281."
  }
]
