[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/3229846",
    "html_url": "https://github.com/ipython/ipython/issues/1191#issuecomment-3229846",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1191",
    "id": 3229846,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMjk4NDY=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-12-21T05:28:20Z",
    "updated_at": "2011-12-21T05:28:20Z",
    "author_association": "MEMBER",
    "body": "The profile is definitely used in the notebook, as are the startup files.  I can confirm that this does work for me (including `from __future__ import division`, and specifying the ipython-dir on the command-line.\n\nNote that you will not see any printed messages from startup scripts in the notebook, because stdout/err that is not associated with notebook execution is not displayed.\n\nCan you post the whole script, and possibly check the javascript console log for any illuminating messages (stdout from your script should be caught under 'IOPub message not from one of my cells' if it ran).\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/3231094",
    "html_url": "https://github.com/ipython/ipython/issues/1191#issuecomment-3231094",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1191",
    "id": 3231094,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMzEwOTQ=",
    "user": {
      "login": "hayne",
      "id": 712769,
      "node_id": "MDQ6VXNlcjcxMjc2OQ==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/712769?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hayne",
      "html_url": "https://github.com/hayne",
      "followers_url": "https://api.github.com/users/hayne/followers",
      "following_url": "https://api.github.com/users/hayne/following{/other_user}",
      "gists_url": "https://api.github.com/users/hayne/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hayne/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hayne/subscriptions",
      "organizations_url": "https://api.github.com/users/hayne/orgs",
      "repos_url": "https://api.github.com/users/hayne/repos",
      "events_url": "https://api.github.com/users/hayne/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hayne/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-12-21T08:37:58Z",
    "updated_at": "2011-12-21T08:37:58Z",
    "author_association": "NONE",
    "body": "Hmm. Now it seems to be working. I'm not sure what I was doing wrong before. This is especially mysterious since I think I ran those two tries I showed in my original report (with and without \"notebook\") one after the other without changing anything in my configuration. \nBut one theory I have is that maybe I had accidentally changed directory so that the folder specified via \"--ipython-dir\" did not exist in the current directory. (I was specifying the ipython-dir via a relative path.) If this had happened, iPython would have helpfully created a new folder with the name I specified and this new folder would of course not have any startup files. I don't think that happened, but I can't see any other explanation for why it wasn't working then and is now.\n\nBut as I said, it now seems to be working.\nI get .666 in the notebook when I evaluate 2 / 3 \nso the \"from **future** import division\" in my \".ipy\" file is taking effect.\n\nThe strange thing is (given what \"minrk\" said above) that I also am now seeing the \"Finished ...\" output from the print statement in my startup \".ipy\" file. This output appears in the notebook cell when I first execute some code in that cell. I.e. the output from the print statement doesn't appear earlier, even though it was issued earlier (as I can see by printing a timestamp).\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/3231848",
    "html_url": "https://github.com/ipython/ipython/issues/1191#issuecomment-3231848",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/1191",
    "id": 3231848,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMzE4NDg=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-12-21T10:05:34Z",
    "updated_at": "2011-12-21T10:05:34Z",
    "author_association": "MEMBER",
    "body": "Ah, thanks for the note - the print statement will come out associated with the first cell because the `stdout.flush()` that draws the line between preflight code and the first cell is happening too early.  The tiny fix necessary is included in PR #1187.\n"
  }
]
