[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/8374002",
    "html_url": "https://github.com/ipython/ipython/issues/2394#issuecomment-8374002",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2394",
    "id": 8374002,
    "node_id": "MDEyOklzc3VlQ29tbWVudDgzNzQwMDI=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-09-07T18:20:09Z",
    "updated_at": "2012-09-07T18:20:09Z",
    "author_association": "MEMBER",
    "body": "Could be the [SuperQObject](https://github.com/ipython/ipython/blob/master/IPython/frontend/qt/util.py#L50) hack needs to be different with PyQt 4.9.  @epatters thoughts?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/8600297",
    "html_url": "https://github.com/ipython/ipython/issues/2394#issuecomment-8600297",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2394",
    "id": 8600297,
    "node_id": "MDEyOklzc3VlQ29tbWVudDg2MDAyOTc=",
    "user": {
      "login": "bfroehle",
      "id": 204333,
      "node_id": "MDQ6VXNlcjIwNDMzMw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/204333?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bfroehle",
      "html_url": "https://github.com/bfroehle",
      "followers_url": "https://api.github.com/users/bfroehle/followers",
      "following_url": "https://api.github.com/users/bfroehle/following{/other_user}",
      "gists_url": "https://api.github.com/users/bfroehle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bfroehle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bfroehle/subscriptions",
      "organizations_url": "https://api.github.com/users/bfroehle/orgs",
      "repos_url": "https://api.github.com/users/bfroehle/repos",
      "events_url": "https://api.github.com/users/bfroehle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bfroehle/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-09-16T22:15:03Z",
    "updated_at": "2012-09-16T22:15:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "@minrk: Doubtful, as my Ubuntu 12.04 installation uses PyQt 4.9.1 and I have never had this issue.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/9758292",
    "html_url": "https://github.com/ipython/ipython/issues/2394#issuecomment-9758292",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2394",
    "id": 9758292,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk3NTgyOTI=",
    "user": {
      "login": "ahhsia",
      "id": 2042495,
      "node_id": "MDQ6VXNlcjIwNDI0OTU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2042495?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ahhsia",
      "html_url": "https://github.com/ahhsia",
      "followers_url": "https://api.github.com/users/ahhsia/followers",
      "following_url": "https://api.github.com/users/ahhsia/following{/other_user}",
      "gists_url": "https://api.github.com/users/ahhsia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ahhsia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ahhsia/subscriptions",
      "organizations_url": "https://api.github.com/users/ahhsia/orgs",
      "repos_url": "https://api.github.com/users/ahhsia/repos",
      "events_url": "https://api.github.com/users/ahhsia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ahhsia/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-10-24T21:54:38Z",
    "updated_at": "2012-10-24T21:54:38Z",
    "author_association": "NONE",
    "body": "Upgrading to sip-4.14 and pyqt-4.9.5 seems to have fixed this problem. I can now start ipython qtconsole\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/9758508",
    "html_url": "https://github.com/ipython/ipython/issues/2394#issuecomment-9758508",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2394",
    "id": 9758508,
    "node_id": "MDEyOklzc3VlQ29tbWVudDk3NTg1MDg=",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-10-24T22:02:09Z",
    "updated_at": "2012-10-24T22:02:09Z",
    "author_association": "MEMBER",
    "body": "shall we chalk this up to a bad PyQt/Qt setup and close, then?\n"
  }
]
