[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10553920",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10553920",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10553920,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNTUzOTIw",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-20T13:31:45Z",
    "updated_at": "2012-11-20T13:31:45Z",
    "author_association": "MEMBER",
    "body": "Is there any way to determine what file it's writing to? I can't think why IPython, matplotlib or readline should be doing a lot of IO on cursor movements.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10554008",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10554008",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10554008,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNTU0MDA4",
    "user": {
      "login": "rkern",
      "id": 46135,
      "node_id": "MDQ6VXNlcjQ2MTM1",
      "avatar_url": "https://avatars3.githubusercontent.com/u/46135?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rkern",
      "html_url": "https://github.com/rkern",
      "followers_url": "https://api.github.com/users/rkern/followers",
      "following_url": "https://api.github.com/users/rkern/following{/other_user}",
      "gists_url": "https://api.github.com/users/rkern/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rkern/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rkern/subscriptions",
      "organizations_url": "https://api.github.com/users/rkern/orgs",
      "repos_url": "https://api.github.com/users/rkern/repos",
      "events_url": "https://api.github.com/users/rkern/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rkern/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-20T13:34:23Z",
    "updated_at": "2012-11-20T13:34:23Z",
    "author_association": "CONTRIBUTOR",
    "body": "`lsof(1)` will show what files are opened by the IPython process. `strace(1)` may give more real-time information about the reads and writes.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10557982",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10557982",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10557982,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNTU3OTgy",
    "user": {
      "login": "jfmoulin",
      "id": 2844284,
      "node_id": "MDQ6VXNlcjI4NDQyODQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844284?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jfmoulin",
      "html_url": "https://github.com/jfmoulin",
      "followers_url": "https://api.github.com/users/jfmoulin/followers",
      "following_url": "https://api.github.com/users/jfmoulin/following{/other_user}",
      "gists_url": "https://api.github.com/users/jfmoulin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jfmoulin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jfmoulin/subscriptions",
      "organizations_url": "https://api.github.com/users/jfmoulin/orgs",
      "repos_url": "https://api.github.com/users/jfmoulin/repos",
      "events_url": "https://api.github.com/users/jfmoulin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jfmoulin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-20T15:07:20Z",
    "updated_at": "2012-11-20T15:07:20Z",
    "author_association": "NONE",
    "body": "Thanks for the tips.\nI am now trying to reproduce the problem, and of course it does not want to appear.\nI'll post a lsof output as soon as I get it again...\nThanks for the fast answers anyway!\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10660674",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10660674",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10660674,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjYwNjc0",
    "user": {
      "login": "ghost",
      "id": 10137,
      "node_id": "MDQ6VXNlcjEwMTM3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghost",
      "html_url": "https://github.com/ghost",
      "followers_url": "https://api.github.com/users/ghost/followers",
      "following_url": "https://api.github.com/users/ghost/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
      "organizations_url": "https://api.github.com/users/ghost/orgs",
      "repos_url": "https://api.github.com/users/ghost/repos",
      "events_url": "https://api.github.com/users/ghost/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghost/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-23T14:21:07Z",
    "updated_at": "2012-11-23T14:21:07Z",
    "author_association": "NONE",
    "body": "I've been plagued by this issue for a while, and I think I have a way to reliably reproduce it.  For me (ipython 0.12 and matplolib 1.0.1 on Fedora 17 under GNOME3 now) the trigger appears to be saving a figure to a file.  This holds true whether it is done using the save button in a matplotlib interactive figure window, via the ipython command line or within code execute with %run.  Before saving a figure ipython responds normally, afterwards every keypress causes lots of disc I/O and the response if unbearably slow.  I hope this information helps, I would love to see a solution to this.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10661430",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10661430",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10661430,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjYxNDMw",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-23T14:48:01Z",
    "updated_at": "2012-11-23T14:48:01Z",
    "author_association": "MEMBER",
    "body": "Thanks, @ajhorton, any hint of a pattern is a step forwards. Unfortunately, I can't replicate the problem, though. This is what I tried:\n\nIPython master, matplotlib master, Ubuntu 12.10\n\n```\nipython --pylab\n\n...\n\nIn [2]: abc = 123  # This was testing responsiveness\n\nIn [3]: plot(arange(10))\nOut[3]: [<matplotlib.lines.Line2D at 0xa3ac6ec>]\n\n# Clicked the save button in the matplotlib window, saved as PNG to the desktop\n\n# (Console remains responsive)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10669265",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10669265",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10669265,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjY5MjY1",
    "user": {
      "login": "jfmoulin",
      "id": 2844284,
      "node_id": "MDQ6VXNlcjI4NDQyODQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844284?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jfmoulin",
      "html_url": "https://github.com/jfmoulin",
      "followers_url": "https://api.github.com/users/jfmoulin/followers",
      "following_url": "https://api.github.com/users/jfmoulin/following{/other_user}",
      "gists_url": "https://api.github.com/users/jfmoulin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jfmoulin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jfmoulin/subscriptions",
      "organizations_url": "https://api.github.com/users/jfmoulin/orgs",
      "repos_url": "https://api.github.com/users/jfmoulin/repos",
      "events_url": "https://api.github.com/users/jfmoulin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jfmoulin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-23T20:41:48Z",
    "updated_at": "2012-11-23T20:41:48Z",
    "author_association": "NONE",
    "body": "Hi!\n\n@ajhorton, you nailed it down! I thought I was trying everything but missed to save a pic.\nUsing pylab.savefig is apparently not a problem but as soon as I save a figure from the GUI I trigger this monster IO activity. I tried several times and the bug always shows up.\n\nI produced a dump of lsof and strace (I'll mail it tgz (200kb) to the takluyver and rkern hoping that this is the right way to proceed... let me know if I could put it online somewhere...).\nJF\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10669452",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10669452",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10669452,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjY5NDUy",
    "user": {
      "login": "jfmoulin",
      "id": 2844284,
      "node_id": "MDQ6VXNlcjI4NDQyODQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844284?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jfmoulin",
      "html_url": "https://github.com/jfmoulin",
      "followers_url": "https://api.github.com/users/jfmoulin/followers",
      "following_url": "https://api.github.com/users/jfmoulin/following{/other_user}",
      "gists_url": "https://api.github.com/users/jfmoulin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jfmoulin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jfmoulin/subscriptions",
      "organizations_url": "https://api.github.com/users/jfmoulin/orgs",
      "repos_url": "https://api.github.com/users/jfmoulin/repos",
      "events_url": "https://api.github.com/users/jfmoulin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jfmoulin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-23T20:51:33Z",
    "updated_at": "2012-11-23T20:51:33Z",
    "author_association": "NONE",
    "body": "Well, me again... I guess the best way is to use something like filebin:\nhttp://filebin.ca/NdspC6wfTV3 links to the tar with the two dumps.\nJF\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10673095",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10673095",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10673095,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjczMDk1",
    "user": {
      "login": "bfroehle",
      "id": 204333,
      "node_id": "MDQ6VXNlcjIwNDMzMw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/204333?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bfroehle",
      "html_url": "https://github.com/bfroehle",
      "followers_url": "https://api.github.com/users/bfroehle/followers",
      "following_url": "https://api.github.com/users/bfroehle/following{/other_user}",
      "gists_url": "https://api.github.com/users/bfroehle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bfroehle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bfroehle/subscriptions",
      "organizations_url": "https://api.github.com/users/bfroehle/orgs",
      "repos_url": "https://api.github.com/users/bfroehle/repos",
      "events_url": "https://api.github.com/users/bfroehle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bfroehle/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-24T02:21:04Z",
    "updated_at": "2012-11-24T02:34:44Z",
    "author_association": "CONTRIBUTOR",
    "body": "Reading through the strace log shows that the program is repeatedly re-creating `/home/jfmoulin/.local/share/recently-used.xbel`.\n\nThe repeated loop appears to be the following.  Now I'm not sure where the loop \"starts\" but I chose what I thought was a reasonable start.\n\n```\nopen(\"/home/jfmoulin/.local/share/recently-used.xbel.05HRNW\", O_RDWR|O_CREAT|O_EXCL, 0666) = 8\nfcntl(8, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)\nfstat(8, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0\nmmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5d2651d000\nlseek(8, 0, SEEK_CUR)                   = 0\nwrite(8, \"<?xml version=\\\"1.0\\\" encoding=\\\"UT\"..., 983040) = 983040\nwrite(8, \"ions>\\n          <bookmark:applic\"..., 3396) = 3396\nfstatfs(8, {f_type=0xf15f, f_bsize=4096, f_blocks=53597515, f_bfree=9962170, f_bavail=7279047, f_files=13418496, f_ffree=13311717, f_fsid={975816597, -635617892}, f_namelen=143, f_frsize=4096}) = 0\nlstat(\"/home/jfmoulin/.local/share/recently-used.xbel\", {st_mode=S_IFREG|0600, st_size=986436, ...}) = 0\nfsync(8)                                = 0\nclose(8)                                = 0\nmunmap(0x7f5d2651d000, 4096)            = 0\nrename(\"/home/jfmoulin/.local/share/recently-used.xbel.05HRNW\", \"/home/jfmoulin/.local/share/recently-used.xbel\") = 0\nchmod(\"/home/jfmoulin/.local/share/recently-used.xbel\", 0600) = 0\nrt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0\nread(0, \"[\", 1)                         = 1\nselect(1, [0], NULL, NULL, {0, 100000}) = 1 (in [0], left {0, 99991})\nfstat(0, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 2), ...}) = 0\nfcntl(0, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\nrecvfrom(10, 0x374eec4, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)\npoll([{fd=11, events=POLLIN}, {fd=10, events=POLLIN}, {fd=5, events=POLLIN}, {fd=7, events=POLLIN}, {fd=0, events=POLLIN}], 5, 0) = 2 ([{fd=11, revents=POLLIN}, {fd=0, revents=POLLIN}])\nread(11, \"\\6\\0\\0\\0\\0\\0\\0\\0\", 16)        = 8\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\nwrite(11, \"\\1\\0\\0\\0\\0\\0\\0\\0\", 8)        = 8\npoll([{fd=10, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}])\nwritev(10, [{\"+\\0\\1\\0\", 4}, {NULL, 0}, {\"\", 0}], 3) = 4\npoll([{fd=10, events=POLLIN}], 1, -1)   = 1 ([{fd=10, revents=POLLIN}])\nrecvfrom(10, \"\\1\\2J#\\0\\0\\0\\0\\5\\0 \\3\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\", 4096, 0, NULL, NULL) = 32\nrecvfrom(10, 0x374eec4, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)\nrecvfrom(10, 0x374eec4, 4096, 0, 0, 0)  = -1 EAGAIN (Resource temporarily unavailable)\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10677796",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10677796",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10677796,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjc3Nzk2",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-24T13:46:32Z",
    "updated_at": "2012-11-24T13:46:32Z",
    "author_association": "MEMBER",
    "body": "Apparently `recently-used.xbel` is something used by GTK. I tried with `ipython --pylab gtk`, and I think I could just see a tiny slowdown after saving a plot. Is there anything notable about that file on your machine - like it being really big, or on a network drive?\n\n@bfroehle , I've had no experience of reading strace logs, but does that mean it's trying to write to the file and failing?\n\nI wonder if the matplotlib guys would have a better idea about debugging this.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10679217",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10679217",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10679217,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjc5MjE3",
    "user": {
      "login": "jfmoulin",
      "id": 2844284,
      "node_id": "MDQ6VXNlcjI4NDQyODQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2844284?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jfmoulin",
      "html_url": "https://github.com/jfmoulin",
      "followers_url": "https://api.github.com/users/jfmoulin/followers",
      "following_url": "https://api.github.com/users/jfmoulin/following{/other_user}",
      "gists_url": "https://api.github.com/users/jfmoulin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jfmoulin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jfmoulin/subscriptions",
      "organizations_url": "https://api.github.com/users/jfmoulin/orgs",
      "repos_url": "https://api.github.com/users/jfmoulin/repos",
      "events_url": "https://api.github.com/users/jfmoulin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jfmoulin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-24T16:20:16Z",
    "updated_at": "2012-11-24T16:20:16Z",
    "author_association": "NONE",
    "body": "/.local/share/recently-used.xbel is 967K  no idea if this has to be considered big. It is on a local disk, which by the way is a ssd... so not the kind of disk you want rewritten in an endless loop.\n Some people apparently try to prevent this file to be used by making it read only, but some temporary files with a similar name might be created though.  \n\nI could reproduce the problem in a normal python shell, so I guess I should post the report on Matplotlib's issue tracker \n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10679413",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10679413",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10679413,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjc5NDEz",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-24T16:41:29Z",
    "updated_at": "2012-11-24T16:41:29Z",
    "author_association": "MEMBER",
    "body": "Yep, I think reporting it to matplotlib is a good idea. Keep us posted\nabout it!\n\nOn 24 November 2012 16:20, jfmoulin notifications@github.com wrote:\n\n> /.local/share/recently-used.xbel is 967K no idea if this has to be\n> considered big. It is on a local disk, which by the way is a ssd... so not\n> the kind of disk you want rewritten in an endless loop.\n> Some people apparently try to prevent this file to be used by making it\n> read only, but some temporary files with a similar name might be created\n> though.\n> \n> I could reproduce the problem in a normal python shell, so I guess I\n> should post the report on Matplotlib's issue tracker\n> \n> —\n> Reply to this email directly or view it on GitHubhttps://github.com/ipython/ipython/issues/2608#issuecomment-10679217.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/10680823",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-10680823",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 10680823,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEwNjgwODIz",
    "user": {
      "login": "bfroehle",
      "id": 204333,
      "node_id": "MDQ6VXNlcjIwNDMzMw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/204333?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bfroehle",
      "html_url": "https://github.com/bfroehle",
      "followers_url": "https://api.github.com/users/bfroehle/followers",
      "following_url": "https://api.github.com/users/bfroehle/following{/other_user}",
      "gists_url": "https://api.github.com/users/bfroehle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bfroehle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bfroehle/subscriptions",
      "organizations_url": "https://api.github.com/users/bfroehle/orgs",
      "repos_url": "https://api.github.com/users/bfroehle/repos",
      "events_url": "https://api.github.com/users/bfroehle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bfroehle/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2012-11-24T17:53:05Z",
    "updated_at": "2012-11-24T17:53:05Z",
    "author_association": "CONTRIBUTOR",
    "body": "Yes, please report it to Matplotlib, but they might send you upstream to PyGTK (or similar).\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22779090",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-22779090",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 22779090,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNzc5MDkw",
    "user": {
      "login": "nachopro",
      "id": 260549,
      "node_id": "MDQ6VXNlcjI2MDU0OQ==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/260549?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nachopro",
      "html_url": "https://github.com/nachopro",
      "followers_url": "https://api.github.com/users/nachopro/followers",
      "following_url": "https://api.github.com/users/nachopro/following{/other_user}",
      "gists_url": "https://api.github.com/users/nachopro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nachopro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nachopro/subscriptions",
      "organizations_url": "https://api.github.com/users/nachopro/orgs",
      "repos_url": "https://api.github.com/users/nachopro/repos",
      "events_url": "https://api.github.com/users/nachopro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nachopro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-16T16:58:17Z",
    "updated_at": "2013-08-16T16:58:17Z",
    "author_association": "NONE",
    "body": "Hi, I have an SSD disk an every times that I press enter under ipython with dummy code (example: In [19]: a = 2), a write disk is maked. It is noticeable for a some lag between press enter and see the result!\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22781128",
    "html_url": "https://github.com/ipython/ipython/issues/2608#issuecomment-22781128",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/2608",
    "id": 22781128,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNzgxMTI4",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-16T17:32:08Z",
    "updated_at": "2013-08-16T17:32:08Z",
    "author_association": "MEMBER",
    "body": "@nachopro : Is this connected to matplotlib, as described in the discussion above? If so, see the matplotlib issue. If not, open a new issue.\n"
  }
]
