[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/36556833",
    "html_url": "https://github.com/ipython/ipython/pull/5158#issuecomment-36556833",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/5158",
    "id": 36556833,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2NTU2ODMz",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-03-03T20:40:53Z",
    "updated_at": "2014-03-03T20:40:53Z",
    "author_association": "MEMBER",
    "body": "Ok, with this PR, we now log the refusal to serve hidden directories, but continues to serve 404 to the user as before. The log message appears right above the 404 that it causes.\n\n```\n2014-03-03 12:34:44.183 [NotebookApp] Refusing to serve hidden directory, via 404 Error\n2014-03-03 12:34:44.184 [tornado.access] WARNING | 404 GET /tree/.hello (127.0.0.1) 1.53ms referer=None\n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/36565453",
    "html_url": "https://github.com/ipython/ipython/pull/5158#issuecomment-36565453",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/5158",
    "id": 36565453,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2NTY1NDUz",
    "user": {
      "login": "ellisonbg",
      "id": 27600,
      "node_id": "MDQ6VXNlcjI3NjAw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/27600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ellisonbg",
      "html_url": "https://github.com/ellisonbg",
      "followers_url": "https://api.github.com/users/ellisonbg/followers",
      "following_url": "https://api.github.com/users/ellisonbg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ellisonbg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ellisonbg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ellisonbg/subscriptions",
      "organizations_url": "https://api.github.com/users/ellisonbg/orgs",
      "repos_url": "https://api.github.com/users/ellisonbg/repos",
      "events_url": "https://api.github.com/users/ellisonbg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ellisonbg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-03-03T22:00:08Z",
    "updated_at": "2014-03-03T22:00:08Z",
    "author_association": "MEMBER",
    "body": "Hmm, I don't see how your changes could cause it, but there is a test failure on travis. I have restarted the tests, but this one is weird (not with the JS tests) and probably worth looking into.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/36569536",
    "html_url": "https://github.com/ipython/ipython/pull/5158#issuecomment-36569536",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/5158",
    "id": 36569536,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2NTY5NTM2",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-03-03T22:36:48Z",
    "updated_at": "2014-03-03T22:36:48Z",
    "author_association": "MEMBER",
    "body": "looks like a real error on my part, fix incoming\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/36578145",
    "html_url": "https://github.com/ipython/ipython/pull/5158#issuecomment-36578145",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/5158",
    "id": 36578145,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2NTc4MTQ1",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-03-04T00:19:21Z",
    "updated_at": "2014-03-04T00:19:21Z",
    "author_association": "MEMBER",
    "body": "Ok, test suite passes now.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/36654551",
    "html_url": "https://github.com/ipython/ipython/pull/5158#issuecomment-36654551",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/5158",
    "id": 36654551,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2NjU0NTUx",
    "user": {
      "login": "ellisonbg",
      "id": 27600,
      "node_id": "MDQ6VXNlcjI3NjAw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/27600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ellisonbg",
      "html_url": "https://github.com/ellisonbg",
      "followers_url": "https://api.github.com/users/ellisonbg/followers",
      "following_url": "https://api.github.com/users/ellisonbg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ellisonbg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ellisonbg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ellisonbg/subscriptions",
      "organizations_url": "https://api.github.com/users/ellisonbg/orgs",
      "repos_url": "https://api.github.com/users/ellisonbg/repos",
      "events_url": "https://api.github.com/users/ellisonbg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ellisonbg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-03-04T18:05:26Z",
    "updated_at": "2014-03-04T18:05:26Z",
    "author_association": "MEMBER",
    "body": "Looks good, thanks.\n"
  }
]
