[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125267176",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125267176",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125267176,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI2NzE3Ng==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:38:32Z",
    "updated_at": "2015-07-27T16:38:32Z",
    "author_association": "MEMBER",
    "body": "@John-Colvin have you done `%matplotlib`? That is typically necessary to avoid matplotlib blocking the eventloop.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125268781",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125268781",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125268781,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI2ODc4MQ==",
    "user": {
      "login": "John-Colvin",
      "id": 1867189,
      "node_id": "MDQ6VXNlcjE4NjcxODk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1867189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/John-Colvin",
      "html_url": "https://github.com/John-Colvin",
      "followers_url": "https://api.github.com/users/John-Colvin/followers",
      "following_url": "https://api.github.com/users/John-Colvin/following{/other_user}",
      "gists_url": "https://api.github.com/users/John-Colvin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/John-Colvin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/John-Colvin/subscriptions",
      "organizations_url": "https://api.github.com/users/John-Colvin/orgs",
      "repos_url": "https://api.github.com/users/John-Colvin/repos",
      "events_url": "https://api.github.com/users/John-Colvin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/John-Colvin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:45:25Z",
    "updated_at": "2015-07-27T16:50:42Z",
    "author_association": "NONE",
    "body": "If `%matplotlib` or `%pylab` are used then the event loop is not blocked, as usual (hence me being able to change content by plotting again). Without the magics the event loop is of course still blocked.\n\nThe problem is that the plot window has frozen, the notebook itself is unaffected.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125269445",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125269445",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125269445,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI2OTQ0NQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:48:46Z",
    "updated_at": "2015-07-27T16:48:46Z",
    "author_association": "MEMBER",
    "body": "And what backend are you using?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125269767",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125269767",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125269767,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI2OTc2Nw==",
    "user": {
      "login": "John-Colvin",
      "id": 1867189,
      "node_id": "MDQ6VXNlcjE4NjcxODk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1867189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/John-Colvin",
      "html_url": "https://github.com/John-Colvin",
      "followers_url": "https://api.github.com/users/John-Colvin/followers",
      "following_url": "https://api.github.com/users/John-Colvin/following{/other_user}",
      "gists_url": "https://api.github.com/users/John-Colvin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/John-Colvin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/John-Colvin/subscriptions",
      "organizations_url": "https://api.github.com/users/John-Colvin/orgs",
      "repos_url": "https://api.github.com/users/John-Colvin/repos",
      "events_url": "https://api.github.com/users/John-Colvin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/John-Colvin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:50:15Z",
    "updated_at": "2015-07-27T16:50:15Z",
    "author_association": "NONE",
    "body": "as mentioned above, the MacOSX backend\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125270051",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125270051",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125270051,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI3MDA1MQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:51:35Z",
    "updated_at": "2015-07-27T16:51:35Z",
    "author_association": "MEMBER",
    "body": "And matplotlib version?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125270524",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125270524",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125270524,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI3MDUyNA==",
    "user": {
      "login": "John-Colvin",
      "id": 1867189,
      "node_id": "MDQ6VXNlcjE4NjcxODk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1867189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/John-Colvin",
      "html_url": "https://github.com/John-Colvin",
      "followers_url": "https://api.github.com/users/John-Colvin/followers",
      "following_url": "https://api.github.com/users/John-Colvin/following{/other_user}",
      "gists_url": "https://api.github.com/users/John-Colvin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/John-Colvin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/John-Colvin/subscriptions",
      "organizations_url": "https://api.github.com/users/John-Colvin/orgs",
      "repos_url": "https://api.github.com/users/John-Colvin/repos",
      "events_url": "https://api.github.com/users/John-Colvin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/John-Colvin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T16:53:55Z",
    "updated_at": "2015-07-27T16:53:55Z",
    "author_association": "NONE",
    "body": "Sorry, should have included that: matplotlib 1.4.3\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125273643",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125273643",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125273643,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI3MzY0Mw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T17:06:45Z",
    "updated_at": "2015-07-27T17:06:45Z",
    "author_association": "MEMBER",
    "body": "Do you have access to a machine with 10.10 stable? I've just run the above steps on:\n- OS X 10.10.4\n- Python 3.4.3\n- matplotlib 1.4.3\n- IPython 3.2.1 (all via conda)\n\nand closing the figure with the x closed the figure as expected. This may be an issue with 10.11. What are your Python and IPython versions, and how are you installing packages?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/125290413",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-125290413",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 125290413,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNTI5MDQxMw==",
    "user": {
      "login": "John-Colvin",
      "id": 1867189,
      "node_id": "MDQ6VXNlcjE4NjcxODk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1867189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/John-Colvin",
      "html_url": "https://github.com/John-Colvin",
      "followers_url": "https://api.github.com/users/John-Colvin/followers",
      "following_url": "https://api.github.com/users/John-Colvin/following{/other_user}",
      "gists_url": "https://api.github.com/users/John-Colvin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/John-Colvin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/John-Colvin/subscriptions",
      "organizations_url": "https://api.github.com/users/John-Colvin/orgs",
      "repos_url": "https://api.github.com/users/John-Colvin/repos",
      "events_url": "https://api.github.com/users/John-Colvin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/John-Colvin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-27T18:06:16Z",
    "updated_at": "2015-07-27T18:06:16Z",
    "author_association": "NONE",
    "body": "Don't have access to a 10.10 box right now, sorry.\n\npython 3.4.3 via homebrew\nmatplotlib 1.4.3 via homebrew\nIpython 3.2.1 via pip\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/126814233",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-126814233",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 126814233,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNjgxNDIzMw==",
    "user": {
      "login": "tacaswell",
      "id": 199813,
      "node_id": "MDQ6VXNlcjE5OTgxMw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/199813?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tacaswell",
      "html_url": "https://github.com/tacaswell",
      "followers_url": "https://api.github.com/users/tacaswell/followers",
      "following_url": "https://api.github.com/users/tacaswell/following{/other_user}",
      "gists_url": "https://api.github.com/users/tacaswell/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tacaswell/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tacaswell/subscriptions",
      "organizations_url": "https://api.github.com/users/tacaswell/orgs",
      "repos_url": "https://api.github.com/users/tacaswell/repos",
      "events_url": "https://api.github.com/users/tacaswell/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tacaswell/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-31T21:17:40Z",
    "updated_at": "2015-07-31T21:17:40Z",
    "author_association": "CONTRIBUTOR",
    "body": "attn @mdehoon \n\nDoes this happen with any other backend?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/155205783",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-155205783",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 155205783,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1NTIwNTc4Mw==",
    "user": {
      "login": "ianlcassidy",
      "id": 6929405,
      "node_id": "MDQ6VXNlcjY5Mjk0MDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6929405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ianlcassidy",
      "html_url": "https://github.com/ianlcassidy",
      "followers_url": "https://api.github.com/users/ianlcassidy/followers",
      "following_url": "https://api.github.com/users/ianlcassidy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ianlcassidy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ianlcassidy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ianlcassidy/subscriptions",
      "organizations_url": "https://api.github.com/users/ianlcassidy/orgs",
      "repos_url": "https://api.github.com/users/ianlcassidy/repos",
      "events_url": "https://api.github.com/users/ianlcassidy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ianlcassidy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-09T21:38:45Z",
    "updated_at": "2015-11-09T21:38:45Z",
    "author_association": "NONE",
    "body": "Has any progress been made on this topic?  I just updated my os x version from 10.10 to 10.11 and this started happening to me.  Here is what I am using:\n\npython 2.7.10 (virtual environment)\nmatplotlib 1.4.3 via pip\nipython 4.0.0 via pip\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/159474266",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-159474266",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 159474266,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1OTQ3NDI2Ng==",
    "user": {
      "login": "ianlcassidy",
      "id": 6929405,
      "node_id": "MDQ6VXNlcjY5Mjk0MDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6929405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ianlcassidy",
      "html_url": "https://github.com/ianlcassidy",
      "followers_url": "https://api.github.com/users/ianlcassidy/followers",
      "following_url": "https://api.github.com/users/ianlcassidy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ianlcassidy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ianlcassidy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ianlcassidy/subscriptions",
      "organizations_url": "https://api.github.com/users/ianlcassidy/orgs",
      "repos_url": "https://api.github.com/users/ianlcassidy/repos",
      "events_url": "https://api.github.com/users/ianlcassidy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ianlcassidy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-25T03:05:38Z",
    "updated_at": "2015-11-25T03:07:48Z",
    "author_association": "NONE",
    "body": "not sure if anyone is still following this ticket, but i found a fix.  installing qt (and pyside) and then using the command `%matplotlib qt` opens a window that can now be closed.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/159487858",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-159487858",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 159487858,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1OTQ4Nzg1OA==",
    "user": {
      "login": "mdehoon",
      "id": 136062,
      "node_id": "MDQ6VXNlcjEzNjA2Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/136062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mdehoon",
      "html_url": "https://github.com/mdehoon",
      "followers_url": "https://api.github.com/users/mdehoon/followers",
      "following_url": "https://api.github.com/users/mdehoon/following{/other_user}",
      "gists_url": "https://api.github.com/users/mdehoon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mdehoon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mdehoon/subscriptions",
      "organizations_url": "https://api.github.com/users/mdehoon/orgs",
      "repos_url": "https://api.github.com/users/mdehoon/repos",
      "events_url": "https://api.github.com/users/mdehoon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mdehoon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-25T04:17:04Z",
    "updated_at": "2015-11-25T04:17:04Z",
    "author_association": "NONE",
    "body": "Does Tkinter work from the notebook? If you do\n\n``` python\n>>> from Tkinter import *\n>>> Tk()\n```\n\ndoes the Tk window appear and function correctly (e.g. resizing, closing)?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/159620186",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-159620186",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 159620186,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1OTYyMDE4Ng==",
    "user": {
      "login": "ianlcassidy",
      "id": 6929405,
      "node_id": "MDQ6VXNlcjY5Mjk0MDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6929405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ianlcassidy",
      "html_url": "https://github.com/ianlcassidy",
      "followers_url": "https://api.github.com/users/ianlcassidy/followers",
      "following_url": "https://api.github.com/users/ianlcassidy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ianlcassidy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ianlcassidy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ianlcassidy/subscriptions",
      "organizations_url": "https://api.github.com/users/ianlcassidy/orgs",
      "repos_url": "https://api.github.com/users/ianlcassidy/repos",
      "events_url": "https://api.github.com/users/ianlcassidy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ianlcassidy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-25T14:20:33Z",
    "updated_at": "2015-11-25T14:21:25Z",
    "author_association": "NONE",
    "body": "@mdehoon as far as i can tell Tkinter is working in my ipython notebook environment (i've never used it before).  i ran through some of the examples in the link below and didn't have a problem with resizing or closing the window.\nhttps://wiki.python.org/moin/Intro%20to%20programming%20with%20Python%20and%20Tkinter\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/159784452",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-159784452",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 159784452,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE1OTc4NDQ1Mg==",
    "user": {
      "login": "mdehoon",
      "id": 136062,
      "node_id": "MDQ6VXNlcjEzNjA2Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/136062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mdehoon",
      "html_url": "https://github.com/mdehoon",
      "followers_url": "https://api.github.com/users/mdehoon/followers",
      "following_url": "https://api.github.com/users/mdehoon/following{/other_user}",
      "gists_url": "https://api.github.com/users/mdehoon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mdehoon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mdehoon/subscriptions",
      "organizations_url": "https://api.github.com/users/mdehoon/orgs",
      "repos_url": "https://api.github.com/users/mdehoon/repos",
      "events_url": "https://api.github.com/users/mdehoon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mdehoon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-26T02:25:05Z",
    "updated_at": "2015-11-26T02:25:05Z",
    "author_association": "NONE",
    "body": "@ianlcassidy  OK, thanks. Have you tried if this bug still appears with the latest version of matplotlib (1.5.0)?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/160033385",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-160033385",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 160033385,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE2MDAzMzM4NQ==",
    "user": {
      "login": "ianlcassidy",
      "id": 6929405,
      "node_id": "MDQ6VXNlcjY5Mjk0MDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6929405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ianlcassidy",
      "html_url": "https://github.com/ianlcassidy",
      "followers_url": "https://api.github.com/users/ianlcassidy/followers",
      "following_url": "https://api.github.com/users/ianlcassidy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ianlcassidy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ianlcassidy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ianlcassidy/subscriptions",
      "organizations_url": "https://api.github.com/users/ianlcassidy/orgs",
      "repos_url": "https://api.github.com/users/ianlcassidy/repos",
      "events_url": "https://api.github.com/users/ianlcassidy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ianlcassidy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-27T03:14:01Z",
    "updated_at": "2015-11-27T03:14:01Z",
    "author_association": "NONE",
    "body": "@mdehoon yes, the bug appears on v1.5.0 of matplotlib.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/160147011",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-160147011",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 160147011,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE2MDE0NzAxMQ==",
    "user": {
      "login": "mdehoon",
      "id": 136062,
      "node_id": "MDQ6VXNlcjEzNjA2Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/136062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mdehoon",
      "html_url": "https://github.com/mdehoon",
      "followers_url": "https://api.github.com/users/mdehoon/followers",
      "following_url": "https://api.github.com/users/mdehoon/following{/other_user}",
      "gists_url": "https://api.github.com/users/mdehoon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mdehoon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mdehoon/subscriptions",
      "organizations_url": "https://api.github.com/users/mdehoon/orgs",
      "repos_url": "https://api.github.com/users/mdehoon/repos",
      "events_url": "https://api.github.com/users/mdehoon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mdehoon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-27T14:08:57Z",
    "updated_at": "2015-11-27T14:08:57Z",
    "author_association": "NONE",
    "body": "@ianlcassidy  How did you get a framework build of Python? Did you follow the guidelines here: http://matplotlib.org/1.5.0/faq/virtualenv_faq.html#osx  ?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/160353880",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-160353880",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 160353880,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE2MDM1Mzg4MA==",
    "user": {
      "login": "ianlcassidy",
      "id": 6929405,
      "node_id": "MDQ6VXNlcjY5Mjk0MDU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/6929405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ianlcassidy",
      "html_url": "https://github.com/ianlcassidy",
      "followers_url": "https://api.github.com/users/ianlcassidy/followers",
      "following_url": "https://api.github.com/users/ianlcassidy/following{/other_user}",
      "gists_url": "https://api.github.com/users/ianlcassidy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ianlcassidy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ianlcassidy/subscriptions",
      "organizations_url": "https://api.github.com/users/ianlcassidy/orgs",
      "repos_url": "https://api.github.com/users/ianlcassidy/repos",
      "events_url": "https://api.github.com/users/ianlcassidy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ianlcassidy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-29T01:29:00Z",
    "updated_at": "2015-11-29T01:29:00Z",
    "author_association": "NONE",
    "body": "@mdehoon no, i just built a virtual environment and then pip installed several packages (including numpy, scipy, ipython, etc.).  i can try to setup another virtual environment and follow some of the steps in the link above.  it's strange that everything was fine with os x 10.10, but then this issue started occurring with os x 10.11.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/160388233",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-160388233",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 160388233,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE2MDM4ODIzMw==",
    "user": {
      "login": "mdehoon",
      "id": 136062,
      "node_id": "MDQ6VXNlcjEzNjA2Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/136062?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mdehoon",
      "html_url": "https://github.com/mdehoon",
      "followers_url": "https://api.github.com/users/mdehoon/followers",
      "following_url": "https://api.github.com/users/mdehoon/following{/other_user}",
      "gists_url": "https://api.github.com/users/mdehoon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mdehoon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mdehoon/subscriptions",
      "organizations_url": "https://api.github.com/users/mdehoon/orgs",
      "repos_url": "https://api.github.com/users/mdehoon/repos",
      "events_url": "https://api.github.com/users/mdehoon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mdehoon/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-29T07:11:12Z",
    "updated_at": "2015-11-29T07:11:12Z",
    "author_association": "NONE",
    "body": "@ianlcassidy  Thank you. Actually I have not been able to reproduce this bug with either 10.10 or 10.11. Also, if your python is not a framework build, then the backend will have other problems as well. For example, clicking the Save button to save the figure to a file will bring up the Save dialog window, but it won't let you edit the file name. With matplotlib 1.5.0, the backend should have warned you that Python is not built as a framework. It may be that the Python you are running is different from what you think it is, or that a different installation of matplotlib is being imported than the intended one. Are you able to compile matplotlib? Then we can check exactly what is going wrong.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/175094887",
    "html_url": "https://github.com/ipython/ipython/issues/8666#issuecomment-175094887",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8666",
    "id": 175094887,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NTA5NDg4Nw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-26T16:11:21Z",
    "updated_at": "2016-01-26T16:11:21Z",
    "author_association": "MEMBER",
    "body": "Closing as it's probably not an IPython bug; feel free to keep using the comments for troubleshooting. We can reopen if it turns out there is something for us to do.\n"
  }
]
